Repository RajashekarRaju/compose-actors, pull requests merged in 2023-04, with the labels that each got.

#56 Upgrade to compose 1.4.1, updated android gradle plugin
  app/build.gradle
  app/src/main/java/com/developersbreach/composeactors/data/datasource/database/DatabaseDataSource.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/home/tabs/MoviesTabContent.kt
  build.gradle
Labels: dependency update

#57 Update navigation, rework modal sheets usages, rework favorites screen feature
  .github/workflows/androidTest.yaml
  .github/workflows/check.yaml
  README.md
  app/build.gradle
  app/src/androidTest/java/com/developersbreach/composeactors/ui/screens/home/HomeScreenUITest.kt
  app/src/main/java/com/developersbreach/composeactors/data/PagedResponse.kt
  app/src/main/java/com/developersbreach/composeactors/data/datasource/database/DatabaseDataSource.kt
  app/src/main/java/com/developersbreach/composeactors/data/datasource/network/JsonRemoteData.kt
  app/src/main/java/com/developersbreach/composeactors/data/datasource/network/NetworkDataSource.kt
  app/src/main/java/com/developersbreach/composeactors/data/datasource/network/RequestUrls.kt
  app/src/main/java/com/developersbreach/composeactors/data/model/HomeOptionItems.kt
  app/src/main/java/com/developersbreach/composeactors/data/repository/actor/ActorRepository.kt
  app/src/main/java/com/developersbreach/composeactors/data/repository/movie/MovieRepository.kt
  app/src/main/java/com/developersbreach/composeactors/domain/GetPagedMovies.kt
  app/src/main/java/com/developersbreach/composeactors/domain/MoviesPagingSource.kt
  app/src/main/java/com/developersbreach/composeactors/ui/components/Components.kt
  app/src/main/java/com/developersbreach/composeactors/ui/components/LazyGridItemsPaging.kt
  app/src/main/java/com/developersbreach/composeactors/ui/components/TabsContainer.kt
  app/src/main/java/com/developersbreach/composeactors/ui/navigation/AppDestinations.kt
  app/src/main/java/com/developersbreach/composeactors/ui/navigation/AppNavigation.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/favorites/FavoriteViewModel.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/favorites/FavoritesScreen.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/favorites/FavoritesScreenUI.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/favorites/FavoritesTopAppBar.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/favorites/NoFavoritesFoundUI.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/favorites/tabs/FavoriteActorsTabContent.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/favorites/tabs/FavoriteMoviesTabContent.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/home/HomeBottomBar.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/home/HomeScreen.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/home/HomeScreenContent.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/home/HomeScreenUI.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/home/HomeUIState.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/home/HomeViewModel.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/home/tabs/ActorsTabContent.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/home/tabs/MoviesTabContent.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/home/tabs/TvShowsTabContent.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/modalSheets/OptionsModalSheetContent.kt
  app/src/main/res/drawable/baseline_developer_mode_24.xml
  app/src/main/res/drawable/baseline_keyboard_arrow_down_24.xml
  app/src/main/res/drawable/baseline_keyboard_arrow_up_24.xml
  app/src/main/res/drawable/baseline_looks_one_24.xml
  app/src/main/res/drawable/ic_account.xml
  app/src/main/res/drawable/ic_arrow_down.xml
  app/src/main/res/drawable/ic_arrow_up.xml
  app/src/main/res/drawable/ic_favorite.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_tv_show.xml
  app/src/main/res/values/strings.xml
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement, refactor

#58 Merge all navigation, bottom sheet, new feature changes into v0.3.0
  app/src/androidTest/java/com/developersbreach/composeactors/ui/screens/home/HomeScreenUITest.kt
  app/src/main/java/com/developersbreach/composeactors/data/model/HomeOptionItems.kt
  app/src/main/java/com/developersbreach/composeactors/ui/components/TabsContainer.kt
  app/src/main/java/com/developersbreach/composeactors/ui/navigation/AppActions.kt
  app/src/main/java/com/developersbreach/composeactors/ui/navigation/AppDestinations.kt
  app/src/main/java/com/developersbreach/composeactors/ui/navigation/AppNavigation.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/favorites/FavoriteViewModel.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/favorites/FavoritesScreen.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/favorites/FavoritesScreenUI.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/favorites/FavoritesTopAppBar.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/favorites/NoFavoritesFoundUI.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/favorites/tabs/FavoriteActorsTabContent.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/favorites/tabs/FavoriteMoviesTabContent.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/home/HomeBottomBar.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/home/HomeScreen.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/home/HomeScreenContent.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/home/HomeScreenUI.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/home/tabs/FavoritesTabContent.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/home/tabs/MoviesTabContent.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/home/tabs/TvShowsTabContent.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/modalSheets/OptionsModalSheetContent.kt
  app/src/main/res/drawable/ic_account.xml
  app/src/main/res/drawable/ic_arrow_down.xml
  app/src/main/res/drawable/ic_arrow_up.xml
  app/src/main/res/drawable/ic_favorite.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_tv_show.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, feature

#59 Improved favorites movie ui improvements
  app/src/main/java/com/developersbreach/composeactors/data/datasource/database/AppDatabase.kt
  app/src/main/java/com/developersbreach/composeactors/data/datasource/database/entity/FavoriteMoviesEntity.kt
  app/src/main/java/com/developersbreach/composeactors/data/datasource/network/JsonRemoteData.kt
  app/src/main/java/com/developersbreach/composeactors/data/model/Movie.kt
  app/src/main/java/com/developersbreach/composeactors/domain/useCase/RemoveMovieFromFavoritesUseCase.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/favorites/FavoriteViewModel.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/favorites/FavoritesScreen.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/favorites/FavoritesScreenUI.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/favorites/tabs/FavoriteMoviesTabContent.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/movieDetail/MovieDetailViewModel.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/movieDetail/MovieDetailsContent.kt
  app/src/main/java/com/developersbreach/composeactors/ui/screens/movieDetail/composables/GetSimilarOrRecommendedMovies.kt
Labels: enhancement, wip
